@startuml
class User {
    + id: Long
    + name: String
    + description: String
    + price: BigDecimal
    + stockQuantity: Integer
    + imageUrl: String
    + category: Category
    + createdAt: LocalDateTime
    + updateAt: LocalDateTime
}
@enduml
